// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbBanner = "tb_banner"

// TbBanner mapped from table <tb_banner>
type TbBanner struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Path      *string        `gorm:"column:path;type:longtext" json:"path"`
	Hash      *string        `gorm:"column:hash;type:longtext" json:"hash"`
	Name      *string        `gorm:"column:name;type:varchar(38)" json:"name"`
}

// TableName TbBanner's table name
func (*TbBanner) TableName() string {
	return TableNameTbBanner
}
