// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbComment = "tb_comment"

// TbComment mapped from table <tb_comment>
type TbComment struct {
	ID              int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt       *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	ParentCommentID *int64         `gorm:"column:parent_comment_id;type:bigint unsigned" json:"parent_comment_id"`
	Content         *string        `gorm:"column:content;type:varchar(256)" json:"content"`
	DiggCount       *int64         `gorm:"column:digg_count;type:tinyint" json:"digg_count"`
	CommentCount    *int64         `gorm:"column:comment_count;type:tinyint" json:"comment_count"`
	ArticleID       *int64         `gorm:"column:article_id;type:bigint unsigned" json:"article_id"`
	UserID          *int64         `gorm:"column:user_id;type:bigint unsigned" json:"user_id"`
}

// TableName TbComment's table name
func (*TbComment) TableName() string {
	return TableNameTbComment
}
