// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

const TableNameTbMenuBanner = "tb_menu_banner"

// TbMenuBanner mapped from table <tb_menu_banner>
type TbMenuBanner struct {
	MenuID   *int64 `gorm:"column:menu_id;type:bigint unsigned" json:"menu_id"`
	BannerID *int64 `gorm:"column:banner_id;type:bigint unsigned" json:"banner_id"`
	Sort     *int64 `gorm:"column:sort;type:smallint" json:"sort"`
}

// TableName TbMenuBanner's table name
func (*TbMenuBanner) TableName() string {
	return TableNameTbMenuBanner
}
