// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbMenu = "tb_menu"

// TbMenu mapped from table <tb_menu>
type TbMenu struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	MenuTitle    *string        `gorm:"column:menu_title;type:varchar(32)" json:"menu_title"`
	MenuTitleEn  *string        `gorm:"column:menu_title_en;type:varchar(32)" json:"menu_title_en"`
	Slogan       *string        `gorm:"column:slogan;type:varchar(64)" json:"slogan"`
	Abstract     *string        `gorm:"column:abstract;type:longtext" json:"abstract"`
	AbstractTime *int64         `gorm:"column:abstract_time;type:bigint" json:"abstract_time"`
	BannerTime   *int64         `gorm:"column:banner_time;type:bigint" json:"banner_time"`
	Sort         *int64         `gorm:"column:sort;type:smallint" json:"sort"`
}

// TableName TbMenu's table name
func (*TbMenu) TableName() string {
	return TableNameTbMenu
}
