// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbMessage = "tb_message"

// TbMessage mapped from table <tb_message>
type TbMessage struct {
	ID                  int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt           *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt           *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	SendUserID          int64          `gorm:"column:send_user_id;type:bigint unsigned;primaryKey" json:"send_user_id"`
	SendUserNickName    *string        `gorm:"column:send_user_nick_name;type:varchar(42)" json:"send_user_nick_name"`
	SendUserAvatar      *string        `gorm:"column:send_user_avatar;type:longtext" json:"send_user_avatar"`
	ReceiveUserID       int64          `gorm:"column:receive_user_id;type:bigint unsigned;primaryKey" json:"receive_user_id"`
	ReceiveUserNickName *string        `gorm:"column:receive_user_nick_name;type:varchar(42)" json:"receive_user_nick_name"`
	ReceiveUserAvatar   *string        `gorm:"column:receive_user_avatar;type:longtext" json:"receive_user_avatar"`
	IsRead              *int64         `gorm:"column:is_read;type:tinyint(1)" json:"is_read"`
	Content             *string        `gorm:"column:content;type:longtext" json:"content"`
}

// TableName TbMessage's table name
func (*TbMessage) TableName() string {
	return TableNameTbMessage
}
