// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbArticle = "tb_article"

// TbArticle mapped from table <tb_article>
type TbArticle struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Title        *string        `gorm:"column:title;type:varchar(32)" json:"title"`
	Abstract     *string        `gorm:"column:abstract;type:longtext" json:"abstract"`
	Content      *string        `gorm:"column:content;type:longtext" json:"content"`
	LookCount    *int64         `gorm:"column:look_count;type:bigint" json:"look_count"`
	CommentCount *int64         `gorm:"column:comment_count;type:bigint" json:"comment_count"`
	DiggCount    *int64         `gorm:"column:digg_count;type:bigint" json:"digg_count"`
	CollectCount *int64         `gorm:"column:collect_count;type:bigint" json:"collect_count"`
	UserID       *int64         `gorm:"column:user_id;type:bigint unsigned" json:"user_id"`
	Category     *string        `gorm:"column:category;type:varchar(20)" json:"category"`
	Source       *string        `gorm:"column:source;type:longtext" json:"source"`
	Link         *string        `gorm:"column:link;type:longtext" json:"link"`
	BannerID     *int64         `gorm:"column:banner_id;type:bigint unsigned" json:"banner_id"`
	NickName     *string        `gorm:"column:nick_name;type:varchar(36)" json:"nick_name"`
	BannerPath   *string        `gorm:"column:banner_path;type:longtext" json:"banner_path"`
	TagArray     *string        `gorm:"column:tag_array;type:varchar(64)" json:"tag_array"`
}

// TableName TbArticle's table name
func (*TbArticle) TableName() string {
	return TableNameTbArticle
}
