// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbFadeBack = "tb_fade_back"

// TbFadeBack mapped from table <tb_fade_back>
type TbFadeBack struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	Email        *string        `gorm:"column:email;type:varchar(350)" json:"email"`
	Content      *string        `gorm:"column:content;type:varchar(128)" json:"content"`
	ApplyContent *string        `gorm:"column:apply_content;type:varchar(128)" json:"apply_content"`
	IsApply      *int64         `gorm:"column:is_apply;type:tinyint(1)" json:"is_apply"`
}

// TableName TbFadeBack's table name
func (*TbFadeBack) TableName() string {
	return TableNameTbFadeBack
}
