// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbLoginDatum = "tb_login_data"

// TbLoginDatum mapped from table <tb_login_data>
type TbLoginDatum struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UserID    *int64         `gorm:"column:user_id;type:bigint unsigned" json:"user_id"`
	IP        *string        `gorm:"column:ip;type:varchar(20)" json:"ip"`
	NickName  *string        `gorm:"column:nick_name;type:varchar(42)" json:"nick_name"`
	Token     *string        `gorm:"column:token;type:varchar(256)" json:"token"`
	Device    *string        `gorm:"column:device;type:varchar(256)" json:"device"`
	Addr      *string        `gorm:"column:addr;type:varchar(64)" json:"addr"`
}

// TableName TbLoginDatum's table name
func (*TbLoginDatum) TableName() string {
	return TableNameTbLoginDatum
}
