// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbUser = "tb_user"

// TbUser mapped from table <tb_user>
type TbUser struct {
	ID         int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt  *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	NickName   *string        `gorm:"column:nick_name;type:varchar(36)" json:"nick_name"`
	UserName   *string        `gorm:"column:user_name;type:varchar(36)" json:"user_name"`
	Password   *string        `gorm:"column:password;type:varchar(128)" json:"password"`
	Avatar     *string        `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	Email      *string        `gorm:"column:email;type:varchar(350)" json:"email"`
	Tel        *string        `gorm:"column:tel;type:varchar(18)" json:"tel"`
	Address    *string        `gorm:"column:address;type:varchar(128)" json:"address"`
	Token      *string        `gorm:"column:token;type:varchar(64)" json:"token"`
	IP         *string        `gorm:"column:ip;type:varchar(20)" json:"ip"`
	Role       *int64         `gorm:"column:role;type:tinyint;default:2" json:"role"`
	SignOrigin *int64         `gorm:"column:sign_origin;type:bigint" json:"sign_origin"`
}

// TableName TbUser's table name
func (*TbUser) TableName() string {
	return TableNameTbUser
}
