// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTbUserCollect = "tb_user_collects"

// TbUserCollect mapped from table <tb_user_collects>
type TbUserCollect struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deleted_at"`
	UserID    int64          `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	ArticleID int64          `gorm:"column:article_id;type:bigint unsigned;primaryKey" json:"article_id"`
}

// TableName TbUserCollect's table name
func (*TbUserCollect) TableName() string {
	return TableNameTbUserCollect
}
